site_name: Simulación de Discos Sólidos

nav:
  - Introducción: index.md
  - Teoría: explanation.md
  - Ejemplos de uso: tutorials.md
  - Documentación técnica: reference.md

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  
  - attr_list  
  - md_in_html
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material
